# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'H-News' do
  pod 'MCSwipeTableViewCell', '~> 2.1.4'
  pod 'Alamofire', '~> 3.0'
  pod 'SnapKit', '~> 0.15.0'
  pod 'CRToast', '~> 0.0.7'

  # You need to add both “Realm” & “RealmSwift”
	pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
  pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'swift-2.0'
end

target 'H-NewsTests' do
  # pod "SwiftMock"
end
