# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'H-News' do
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'CRToast'
  pod 'BEMCheckBox'
  pod 'RealmSwift'
  pod 'Kanna', '~> 2.1.0'
end
